In [1]:
import pandas as pd

data=pd.read_csv("finance_data_100.csv")

data

,Company,Sector,Stock Price,Market Cap,P/E Ratio,Dividend Yield (%),Credit Rating,Currency
0,Bajaj,Retail,3686.17,7.366985e+10,33.34,2.09,A,EUR
1,TCS,Retail,1982.93,5.890935e+11,18.96,1.08,BBB,INR
2,SBI,Energy,255.30,4.056468e+10,21.28,4.56,A,USD
3,Bajaj,IT,2994.74,2.614755e+12,6.99,1.80,BBB,EUR
4,Bajaj,Banking,4288.56,1.591654e+12,34.25,0.61,AAA,USD
...,...,...,...,...,...,...,...,...
95,HDFC,Energy,1827.03,8.216407e+11,10.66,4.28,AA,EUR
96,Bajaj,Energy,215.89,9.731065e+10,9.51,0.50,AA,EUR
97,HDFC,IT,1062.17,1.025667e+12,18.49,4.49,BB,USD
98,SBI,Finance,4027.07,3.420755e+12,37.80,3.75,AAA,USD
99,Bajaj,Retail,3352.15,2.771753e+12,24.22,3.26,BB,USD

In [2]:
data.head()

,Company,Sector,Stock Price,Market Cap,P/E Ratio,Dividend Yield (%),Credit Rating,Currency
0,Bajaj,Retail,3686.17,7.366985e+10,33.34,2.09,A,EUR
1,TCS,Retail,1982.93,5.890935e+11,18.96,1.08,BBB,INR
2,SBI,Energy,255.30,4.056468e+10,21.28,4.56,A,USD
3,Bajaj,IT,2994.74,2.614755e+12,6.99,1.80,BBB,EUR
4,Bajaj,Banking,4288.56,1.591654e+12,34.25,0.61,AAA,USD

In [3]:
data.tail()

,Company,Sector,Stock Price,Market Cap,P/E Ratio,Dividend Yield (%),Credit Rating,Currency
95,HDFC,Energy,1827.03,8.216407e+11,10.66,4.28,AA,EUR
96,Bajaj,Energy,215.89,9.731065e+10,9.51,0.50,AA,EUR
97,HDFC,IT,1062.17,1.025667e+12,18.49,4.49,BB,USD
98,SBI,Finance,4027.07,3.420755e+12,37.80,3.75,AAA,USD
99,Bajaj,Retail,3352.15,2.771753e+12,24.22,3.26,BB,USD

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Company             100 non-null    object
 1   Sector              100 non-null    object
 2   Stock Price         100 non-null    float64
 3   Market Cap          100 non-null    float64
 4   P/E Ratio           100 non-null    float64
 5   Dividend Yield (%)  100 non-null    float64
 6   Credit Rating       100 non-null    object
 7   Currency            100 non-null    object
dtypes: float64(4), object(4)
memory usage: 6.4+ KB

In [5]:
data.describe()

       Stock Price    Market Cap   P/E Ratio  Dividend Yield (%)
count   100.000000  1.000000e+02  100.000000          100.000000
mean   2471.596000  1.264673e+12   24.201000            2.749700
std    1416.227128  1.168018e+12   10.239509            1.281482
min     215.890000  7.910067e+09    5.460000            0.500000
25%    1148.527500  2.876951e+11   16.617500            1.647500
50%    2477.820000  9.595477e+11   24.095000            2.850000
75%    3451.047500  1.740579e+12   33.387500            3.810000
max    4912.790000  4.376381e+12   39.940000            4.810000

In [6]:
data.isnull()

,Company,Sector,Stock Price,Market Cap,P/E Ratio,Dividend Yield (%),Credit Rating,Currency
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False

In [7]:
data.isnull().sum

Company               0
Sector                0
Stock Price           0
Market Cap            0
P/E Ratio             0
Dividend Yield (%)    0
Credit Rating         0
Currency              0
dtype: int64

In [8]:
B1=data["Sector"].mode()
B1

0    Banking
1     Retail
Name: Sector, dtype: object

In [9]:
D1=data["Market Cap"].mean()
D1

1264673112212.4104

In [10]:
C1=data["Currency"].mode()
C1

0    EUR
1    USD
Name: Currency, dtype: object

In [11]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

data["Credit Rating"] = label_encoder.fit_transform(data["Credit Rating"])
data

,Company,Sector,Stock Price,Market Cap,P/E Ratio,Dividend Yield (%),Credit Rating,Currency
0,Bajaj,Retail,3686.17,7.366985e+10,33.34,2.09,0,EUR
1,TCS,Retail,1982.93,5.890935e+11,18.96,1.08,4,INR
2,SBI,Energy,255.30,4.056468e+10,21.28,4.56,0,USD
3,Bajaj,IT,2994.74,2.614755e+12,6.99,1.80,4,EUR
4,Bajaj,Banking,4288.56,1.591654e+12,34.25,0.61,2,USD
...,...,...,...,...,...,...,...,...
95,HDFC,Energy,1827.03,8.216407e+11,10.66,4.28,1,EUR
96,Bajaj,Energy,215.89,9.731065e+10,9.51,0.50,1,EUR
97,HDFC,IT,1062.17,1.025667e+12,18.49,4.49,3,USD
98,SBI,Finance,4027.07,3.420755e+12,37.80,3.75,2,USD
99,Bajaj,Retail,3352.15,2.771753e+12,24.22,3.26,3,USD

In [50]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

data["Currency"] = label_encoder.fit_transform(data["Currency"])
data

,Company,Sector,Stock Price,Market Cap,P/E Ratio,Dividend Yield (%),Credit Rating,Currency
0,Bajaj,Retail,3686.17,7.366985e+10,33.34,2.09,A,0
1,TCS,Retail,1982.93,5.890935e+11,18.96,1.08,BBB,1
2,SBI,Energy,255.30,4.056468e+10,21.28,4.56,A,2
3,Bajaj,IT,2994.74,2.614755e+12,6.99,1.80,BBB,0
4,Bajaj,Banking,4288.56,1.591654e+12,34.25,0.61,AAA,2
...,...,...,...,...,...,...,...,...
95,HDFC,Energy,1827.03,8.216407e+11,10.66,4.28,AA,0
96,Bajaj,Energy,215.89,9.731065e+10,9.51,0.50,AA,0
97,HDFC,IT,1062.17,1.025667e+12,18.49,4.49,BB,2
98,SBI,Finance,4027.07,3.420755e+12,37.80,3.75,AAA,2
99,Bajaj,Retail,3352.15,2.771753e+12,24.22,3.26,BB,2

In [51]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

data["Credit Rating"] = label_encoder.fit_transform(data["Credit Rating"])
data

,Company,Sector,Stock Price,Market Cap,P/E Ratio,Dividend Yield (%),Credit Rating,Currency
0,Bajaj,Retail,3686.17,7.366985e+10,33.34,2.09,0,0
1,TCS,Retail,1982.93,5.890935e+11,18.96,1.08,4,1
2,SBI,Energy,255.30,4.056468e+10,21.28,4.56,0,2
3,Bajaj,IT,2994.74,2.614755e+12,6.99,1.80,4,0
4,Bajaj,Banking,4288.56,1.591654e+12,34.25,0.61,2,2
...,...,...,...,...,...,...,...,...
95,HDFC,Energy,1827.03,8.216407e+11,10.66,4.28,1,0
96,Bajaj,Energy,215.89,9.731065e+10,9.51,0.50,1,0
97,HDFC,IT,1062.17,1.025667e+12,18.49,4.49,3,2
98,SBI,Finance,4027.07,3.420755e+12,37.80,3.75,2,2
99,Bajaj,Retail,3352.15,2.771753e+12,24.22,3.26,3,2

In [52]:
empty_cells = data.isnull().sum()
print(empty_cells)

Company               0
Sector                0
Stock Price           0
Market Cap            0
P/E Ratio             0
Dividend Yield (%)    0
Credit Rating         0
Currency              0
dtype: int64

In [53]:
X=data.drop(["Market Cap","Sector","Company","Stock Price","Currency","Credit Rating"],axis=1)
y=data["Credit Rating"]

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [55]:
X_train.head()

    P/E Ratio  Dividend Yield (%)
55      37.33                3.77
88       6.37                3.68
26      30.40                2.80
42       5.46                1.17
69      36.67                3.09

In [56]:
X_test.head()

    P/E Ratio  Dividend Yield (%)
83      21.79                2.19
53      19.33                4.06
70      22.56                3.65
45      24.25                2.57
44      36.27                1.35

In [57]:
y_train.head()

55    3
88    4
26    0
42    1
69    2
Name: Credit Rating, dtype: int32

In [58]:
y_test.head()

83    2
53    4
70    0
45    0
44    2
Name: Credit Rating, dtype: int32

In [59]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [60]:
ypre=model.predict(X_test)
print(ypre)

[2.204025   1.98442702 2.02582709 2.15197856 2.26912874 2.25738951
 2.09121975 2.41783147 2.21316367 2.18713521 2.06988002 1.88905016
 2.01991645 2.22466    1.95466484 2.36353495 1.98477285 2.14543891
 2.34166131 2.24490421]

In [61]:
y_test

83    2
53    4
70    0
45    0
44    2
39    3
22    0
80    0
10    3
0     0
18    1
30    2
73    3
33    3
90    2
4     2
76    1
77    0
12    4
31    3
Name: Credit Rating, dtype: int32